Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -54,5 +54,6 @@ runs:
         test_url=$([[ "$test_url" == "true" ]] && echo "https://www.google.com" || echo "$test_url")
         ip=$(curl -s https://api.ip.sb/ip || curl -s https://ifconfig.me)
         latency=$(curl -o /dev/null -s -w "%{time_starttransfer}" "$test_url" 2>/dev/null)
-        echo "@Proxy -> IP: $ip | Latency (TTFB to $test_url): $([[ -n "$latency" ]] && echo "${latency}s" || echo "Fail")"
+        latency_ms=$([[ -n "$latency" ]] && awk "BEGIN {printf \"%.0f\", $latency * 1000}" || echo "")
+        echo "@Proxy -> IP: $ip | Latency (TTFB to $test_url): $([[ -n "$latency" ]] && echo "${latency_ms}ms" || echo "Fail")"
 
